### ISSUE TITLE
Monolog 3 support

### ISSUE THREAD

**Issue by phatshambler** [pubnub/php#79]
Hi,

We have to upgrade to Monolog 3 which is a Laravel 10 dependency and Pubnub PHP is not compatible with this newer version. Do you have plans to upgrade it or remove the dependency as mentioned here [DEVELOPER.md](https://github.com/pubnub/php/blob/master/DEVELOPER.md)?

Thanks!

**Comment by seba-aln** [comment]
Hey. Thanks for pointing this out. I'll try to look at this issue in the coming days. Probably will have to rewrite DEVELOPER.md because it looks a bit outdated by now. 
We're always open for feedback so feel free to contact us.

**Comment by seba-aln** [comment]
For testing purposes I've added a dependency for `monolog\monolog@3.0` and all the tests pass. 
In the meantime logger for PubNub SDK instances are injected through external dependency and can be anything implementing `Psr\Log\LoggerInterface` to comply with [PSR3](https://www.php-fig.org/psr/psr-3/)

Example:

```
$pubnub->setLogger($myLogger);
```
